# Generated by Django 3.1.7 on 2021-04-01 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_auto_20210322_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='U',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='pozycja')),
            ],
            options={
                'verbose_name': 'U',
                'verbose_name_plural': 'Us',
            },
        ),
    ]
