# Generated by Django 3.1.7 on 2021-08-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_auto_20210829_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Port',
        ),
    ]
