# Generated by Django 3.1.7 on 2021-08-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210827_0147'),
        ('cabinet', '0003_delete_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('defaultobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.defaultobject')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.device', verbose_name='device')),
            ],
            options={
                'verbose_name': 'Port',
                'verbose_name_plural': 'Ports',
            },
            bases=('core.defaultobject', models.Model),
        ),
    ]
