# Generated by Django 3.1.3 on 2021-03-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_defaultobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultobject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
    ]
