# Generated by Django 3.1.7 on 2021-08-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210322_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultobject',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Nazwa'),
        ),
    ]
