# Generated by Django 3.1.7 on 2021-08-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210827_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultobject',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Nazwa'),
        ),
    ]
